#!/bin/bash
clear
[[ "$(whoami)" != "root" ]] && {
echo -e "\033[1;33m[\033[1;31mErro\033[1;33m] \033[1;37m- \033[1;33mvocê precisa executar como root\033[0m"
rm $HOME/Plus > /dev/null 2>&1; exit 0
apt-get update -y
apt-get upgrade -y
apt-get install stunnel4 -y
apt-get install stunnel -y
openssl genrsa 1024 > stunnel.key
openssl req -new -key stunnel.key -x509 -days 1000 -out stunnel.crt
#fica apertando enter os passos seguinte 
cat stunnel.crt stunnel.key > stunnel.pem
mv stunnel.pem /etc/stunnel/
