#!/bin/bash
apt-get update -y
apt-get upgrade -y
apt-get install stunnel4 -y
apt-get install stunnel -y
openssl genrsa 1024 > stunnel.key
openssl req -new -key stunnel.key -x509 -days 1000 -out stunnel.crt
#fica apertando enter os passos seguinte 
cat stunnel.crt stunnel.key > stunnel.pem
mv stunnel.pem /etc/stunnel/
