#! / bin / bash
if [ -d  " / etc / squid / " ] ;  then
    payload = " /etc/squid/payload.txt "
elif [ -d  " / etc / squid3 / " ] ;  then
	payload = " /etc/squid3/payload.txt "
fi
tput setaf 7 ; tput setab 4 ; tput bold ;  printf  ' % 35s% s% -10s \ n '  " Add Host to Squid Proxy "  ; tput sgr0
if [ !  -f  " $ payload " ]
then
	tput setaf 7 ; tput setab 4 ; tput bold ;  echo  " "  ;  Echo  " Arquivo $ payload não found "  ; tput sgr0
	exit 1
else
	tput setaf 2 ; tput bold ;  echo  " " ;  echo  " Domains atuais not file $ payload : "  ; tput sgr0
	tput setaf 3 ; tput bold ;  echo  " "  ; cat $ payload  ;  echo  " "  ; tput sgr0
	read -p " Type or domain you want to add to list: " host
	if [[ -z  $ host ]]
	then
		tput setaf 7 ; tput setab 4 ; tput bold ;  echo  " "  ;  echo  " Você digitou um vazio domain or not existing! "  ;  echo  " "  ; tput sgr0
		exit 1
	else
		if [[ ` grep -c " ^ $ host "  $ payload `  eq 1]]
		then
			tput setaf 7 ; tput setab 4 ; tput bold ;  echo  " "  ;  echo  " Or domain $ host does not exist $ payload file "  ;  echo  " "  ; tput sgr0
			exit 1
		else
			if [[ $ host  ! =  \. * ]]
			then
				tput setaf 7 ; tput setab 4 ; tput bold ;  echo  " "  ;  echo  " You must add a domain starting-or as a point! "  ;  echo  " For example: .phreaker56.xyz "  ;  echo  "It is not necessary to add subdomains for domains that are not yet archived "  ;  echo  " Ou seja, it is not necessary to add rechargewap.claro.com.br "  ;  echo  " se or domain .claro.com.br já estiver no file. "  ;  echo  "; tput sgr0
				exit 1
			else
				echo  " $ host "  >>  $ payload  && grep -v " ^ $ "  $ payload  > / tmp / a && mv / tmp / a $ payload
				tput setaf 7 ; tput setab 1 ; tput bold ;  echo  " "  ;  echo  " File $ payload updated, or domain was added with success: "  ; tput sgr0
				tput setaf 3 ; tput bold ;  echo  " "  ; cat $ payload  ;  echo  " "  ; tput sgr0
				if [ !  -f  " /etc/init.d/squid3 " ]
				then
					service squid3 reload
				elif [ !  -f  " /etc/init.d/squid " ]
				then
					service squid reload
				fi	
				tput setaf 7 ; tput setab 1 ; tput bold ;  echo  " "  ;  echo  " O Proxy Squid Proxy was reloaded with success! "  ;  echo  " "  ; tput sgr0
				exit 1
			fi
		fi
	fi
fi
