#! / bin / bash
[[ !  -d / etc / SSHPlus]] &&  exit 0
[[ !  -d / etc / bot / resell]] &&  exit 0
[[ " $ ( ls / etc / bot / resell | wc -l ) "  ==  ' 0 ' ]] &&  exit 0
for  arq  in  $ ( ls / etc / bot / resell ) ;  do
	_diasR = $ ( grep -w ' RESELL_DAYS ' / etc / bot / resell / $ arq / $ arq  | awk ' {print $ NF} ' )
	[[ " $ _diasR "  -eq  ' 0 ' ]] && {
		[[ " $ ( grep -wc ' SUBSELL ' / etc / bot / resell / $ arq / $ arq ) "  ! =  ' 0 ' ]] && {
			while  read _listsub3 ;  do
				_usub3 = " $ ( echo $ _listsub3  | awk ' {print $ 2} ' ) "
				_dir_users = " / etc / bot / resell / $ _usub3 / users "
				[[ " $ ( ls $ _dir_users  | wc -l ) "  ! =  ' 0 ' ]] && {
					for  _user  in  $ ( ls $ _dir_users ) ;  do
						usermod -L $ _user
						pkill -U $ _user
					done
				}
				[[ $ ( grep -wc $ _usub3 / etc / bot / suspensions_list )  ==  ' 0 ' ]] && {
					[[ !  -z  $ _usub3 ]] && {
						echo  $ _usub3 suspense
						mv / etc / bot / resell / $ _usub3 / etc / bot / suspensos / $ _usub3
						grep -w " $ _usub3 " / etc / bot / asset_list >> / etc / bot / suspensory_list
					}
				}
			done  <<< " $ (grep -w 'SUBSELL' / etc / bot / resell / $ arq / $ arq) "
		}
		[[ " $ ( ls / etc / bot / resell / $ arq / users | wc -l ) "  ! =  ' 0 ' ]] && {
			for  _user  in  $ ( ls / etc / bot / resell / $ arq / users ) ;  do
				usermod -L $ _user
				pkill -U $ _user
			done
		}
		[[ $ ( grep -wc $ arq / etc / bot / suspensions_list )  ==  ' 0 ' ]] && {
			[[ !  -z  $ arq ]] && {
				echo  $ arq suspense
				mv / etc / bot / resell / $ arq / etc / bot / suspensos / $ arq
				grep -w " $ arq " / etc / bot / asset_list >> / etc / bot / suspensory_list
			}
		}
		echo  " $ arq ~ $ _diasR "
	} || {
		_days = $ (( $ _diasR  -  1 ))
		sed -i " / \ b $ arq \ b / s / DAYS: $ _diasR / DAYS: $ _days / " / etc / bot / asset_list
		sed -i " / DIAS_REVENDA / s / $ _diasR / $ _days / " / etc / bot / resell / $ arq / $ arq
		echo  $ arq  $ _diasR DAYS ALTERED TO $ _days
	}
done
