#!/bin/bash
#====================================================
#	SCRIPT: CONEXAO SSHPLUS MANAGER
#   DATA ATT:   28 de Set 2020
#	DESENVOLVIDO POR:	CRAZY_VPN
#	CONTATO TELEGRAM:	http://t.me/crazy_vpn
#	CANAL TELEGRAM:	http://t.me/sshplus
#====================================================
_lvk=$(wget -qO- https://raw.githubusercontent.com/Vanderlei-ctrl/shellscript/master/Install/versao)
IP=$(wget -qO- ipv4.icanhazip.com)
IP2=$(wget -qO- http://whatismyip.akamai.com/)
[[ "$IP" != "$IP2" ]] && ipdovps="$IP2" || ipdovps="$IP"
echo -e "$ipdovps" >/etc/IP
