#!/bin/bash
#Menu Adaptado Completo

#Donwload
wget -O /bin/menu https://raw.githubusercontent.com/Vanderlei-ctrl/shellscript/master/Install/Menu_UP/menuV2/menuV2 > /dev/null 2>&1

#Permisos
chmod +x /bin/menu

#Ejecucion
/bin/menu

#fim
