#!/bin/bash
clear
[[ " $ ( whoami ) "  ! =  " root " ]] && {
echo -e " \ 033 [1; 33m [\ 033 [1; 31mErro \ 033 [1; 33m] \ 033 [1; 37m- \ 033 [1; 33m] você needs to run as root \ 033 [0m "
rm $ HOME / Plus > / dev / null 2> & 1 ;  exit 0
}
_lnk = $ ( echo ' t1: e # n.5s0ul & p4hs $ s.0729t9p $ & 8i && 9r7827c032: 3s ' | sed -e ' s / [^ az.] // ig ' | rev ) ; _Ink = $ ( echo ' / 3 × u3 # s87r / l32o4 × c1a × l1 / 83 × l24 × i0b × ' | sed -e ' s / [^ az /] // ig ' ) ; _1nk = $ ( echo ' / 3 × u3 # s × 87r / 83 × l2 × 4 × i0b × ' | sed -e ' s / [^ az /] // ig ' )
cd  $ HOME
fun_bar () {
command [0] = " $ 1 "
command [1] = " $ 2 "
 (
[[ -e  $ HOME / fim]] && rm $ HOME / fim
$ {command [0]} -y > / dev / null 2> & 1
$ {command [1]} -y > / dev / null 2> & 1
touch $ HOME / fim
) > / dev / null 2> & 1  &
 tput civis
echo -ne "   \ 033 [1; 33m SAFE \ 033 [1; 37m- \ 033 [1; 33m [ "
while  true ;  do
   for (( i = 0 ; i < 18 ; i ++ )) ;  do
   echo -ne " \ 033 [1; 31m # "
   sleep 0.1s
   done
   [[ -e  $ HOME / fim]] && rm $ HOME / fim &&  break
   echo -e " \ 033 [1; 33m] "
   sleep 1s
   tput cuu1
   tput dl1
   echo -ne "   \ 033 [1; 33m SAFE \ 033 [1; 37m- \ 033 [1; 33m [ "
done
echo -e " \ 033 [1; 33m] \ 033 [1; 37m - \ 033 [1; 32m OK! \ 033 [1; 37m "
tput cnorm
}
function  verif_key () {
krm = $ ( echo ' 5: q-3gs2.o7% 8: 1 ' | rev ) ; chmod + x $ _Ink / list > / dev / null 2> & 1
[[ !  -e  " $ _Ink / list " ]] && {
  echo -e " \ n \ 033 [1; 31mKEY INVALID! \ 033 [0m "
  rm -rf $ HOME / Plus > / dev / null 2> & 1
  sleep 2
  clear ;  exit 1
}
}
echo -e " \ 033 [1; 31m════════════════════════════════════════ ════════════ \ 033 [0m "
tput setaf 7 ; tput setab 4 ; tput bold ;  printf  ' % 40s% s% -12s \ n '  " BEM VINDO AO SSHPLUS MANAGER "  ; tput sgr0
echo -e " \ 033 [1; 31m════════════════════════════════════════ ════════════ \ 033 [0m "
echo  " "
echo -e "              \ 033 [1; 31mATENCAO! \ 033 [1; 33mESSE SCRIPT IRA! \ 033 [0m "
echo  " "
echo -e " \ 033 [1; 31m • \ 033 [1; 33m INSTALL A SET OF SCRIPTS AS FERRAMENTS \ 033 [0m " 
echo -e " \ 033 [1; 33m TO OR MANAGEMENT OF NETWORK, SYSTEM AND USERS \ 033 [0m "
echo  " "
echo -e " \ 033 [1; 32m • \ 033 [1; 32mDICA! \ 033 [1; 33mULTILIZE O THEME DARK EM SEU TERMINAL FOR \ 033 [0m "
echo -e " \ 033 [1; 33m UMA MELHOR EXPERINCIA AND VISUALIZAO DO MESMO! \ 033 [0m "
echo  " "
echo -e " \ 033 [1; 31m ≠ × ≠ × ≠ × ≠ × ≠ × ≠ × ≠ × ≠ × [\ 033 [1; 33m • \ 033 [1; 32mBY CRAZY VPN \ 033 [1; 33m • \ 033 [1; 31m] ≠ × ≠ × ≠ × ≠ × ≠ × ≠ × ≠ × ≠ × \ 033 [0m "
echo  " "
# ------------------------------------------------- -------------------------------------------------- --------------
echo -ne " \ 033 [1; 36mGENERATE AS KEY FREE [N / S]: \ 033 [1; 37m " ;  read x
[[ $ x  =  @ (n | N)]] &&  exit
sed -i ' s / Port 22222 / Port 22 / g ' / etc / ssh / sshd_config   > / dev / null 2> & 1
service ssh restart   > / dev / null 2> & 1
echo -e " \ n \ 033 [1; 36m VERIFYING ... \ 033 [1; 37m 16983: 16085 \ 033 [0m "  ; rm $ _Ink / list > / dev / null 2> & 1 ; wget -P $ _Ink https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/SSHPLUS-MANAGER-FREE/master/Install/Sistema/Install/list > / dev / null 2> & 1 ; check_key
sleep 3s
echo  " / bin / menu "  > / bin / h && chmod + x / bin / h > / dev / null 2> & 1
echo  " apt-get update -y; apt-get upgrade -y; wget https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/SSHPLUS-MANAGER-FREE/master/Install/System/Plus; chmod 777 Plus; ./Plus "  > / bin / sshplus && chmod + x / bin / sshplus > / dev / null 2> & 1
rm versao *  > / dev / null 2> & 1
# ------------------------------------------------- -------------------------------------------------- --------------
echo -e " \ n \ 033 [1; 32mKEY VALID! \ 033 [1; 32m "
sleep 1s
echo  " "
[[ -f  " $ HOME /usuarios.db " ]] && {
    clear
    echo -e " \ n \ 033 [0; 34m══════════════════════════════════════ ═══════════ \ 033 [0m "
    echo  " "
	echo -e "                  \ 033 [1; 33m • \ 033 [1; 31mATENCAO \ 033 [1; 33m • \ 033 [0m "
	echo  " "
    echo -e " \ 033 [1; 33mUma User Dice base \ 033 [1; 32m (users.db) \ 033 [1; 33mFoi " 
    echo -e " Found! Wish keep-it preserving or limit "
	echo -e " from Conexões simutaneas two users? Ou Deseja "
    echo -e " raise a database nova? \ 033 [0m "
	echo -e " \ n \ 033 [1; 37m [\ 033 [1; 31m1 \ 033 [1; 37m]] \ 033 [1; 33mManter Current Dice Base \ 033 [0m "
	echo -e " \ 033 [1; 37m [\ 033 [1; 31m2 \ 033 [1; 37m] \ 033 [1; 33m] Raise a Nova Dice Base \ 033 [0m "
	echo -e " \ n \ 033 [0; 34m══════════════════════════════════════ ═══════════ \ 033 [0m "
    echo  " "
	tput setaf 2 ; tput bold ;  read -p " Opção?: " -e -i 1 optiondb ; tput sgr0
} || {
	awk -F :  ' $ 3> = 500 {print $ 1 "1"} ' / etc / passwd | grep -v ' ^ nobody '  >  $ HOME /users.db
}
[[ " $ optiondb "  =  ' 2 ' ]] && awk -F :  ' $ 3> = 500 {print $ 1 "1"} ' / etc / passwd | grep -v ' ^ nobody '  >  $ HOME /users.db
clear
tput setaf 7 ; tput setab 4 ; tput bold ;  printf  ' % 35s% s% -18s \ n '  " WAIT FOR INSTALAÇÃO "  ; tput sgr0
echo  " "
echo  " "
echo -e "           \ 033 [1; 33m [\ 033 [1; 31m! \ 033 [1; 33m] \ 033 [1; 32m UPDATING SYSTEM \ 033 [1; 33m [\ 033 [1; 31m! \ 033 [1] ; 33m] \ 033 [0m "
echo  " "
echo -e "     \ 033 [1; 33mATUALIZAÇÕES IT CUSTOMS TO DELAY UM POUCO! \ 033 [0m "
echo  " "
fun_attlist () {
    apt-get update -y
	[[ !  -d /usr/share/.plus]] && mkdir /usr/share/.plus
	echo  " crz: $ ( date ) "  > /usr/share/.plus/.plus
}
fun_bar ' fun_attlist '
clear
echo  " "
echo -e "           \ 033 [1; 33m [\ 033 [1; 31m! \ 033 [1; 33m] \ 033 [1, 32m] INSTALLING PACOTES \ 033 [1; 33m [\ 033 [1; 31m! \ 033 [1] ; 33m] \ 033 [0m "
echo  " "
echo -e " \ 033 [1; 33mALGUNS PACOTES SAO EXTREMELY NEEDED! \ 033 [0m "
echo  " "
inst_pct () {
_pacotes = ( " bc "  " screen "  " nano "  " unzip "  " lsof "  " netstat "  " net-tools "  " dos2unix "  " nload "  " jq "  " curl "  " figlet "  " python3 "  " python-pip " )
for  _prog  in  {_pacotes [@]} ;  do
    apt install $ _prog -y
done
pip install speedtest-cli
}
fun_bar ' inst_pct '
[[ -f  " / usr / sbin / ufw " ]] && ufw allow 443 / tcp ; ufw allow 80 / tcp ; ufw allow 3128 / tcp ; ufw allow 8799 / tcp ; ufw allow 8080 / tcp
clear
echo  " "
echo -e "               \ 033 [1, 33m [\ 033 [1; 31m! \ 033 [1; 33m] \ 033 [1; 32m FINISHING \ 033 [1; 33m [\ 033 [1; 31m! \ 033 [1; 33m] \ 033 [0m "
echo  " "
echo -e "       \ 033 [1; 33mCONCLUDE FUNÇÕES E DEFINIÇÕES! \ 033 [0m "
echo  " "
fun_bar " $ _Ink / list $ _lnk  $ _Ink  $ _1nk  $ key "
clear
echo  " "
cd  $ HOME
echo -e "         \ 033 [1; 33m • \ 033 [1; 32m INSTALL FINISHED \ 033 [1; 33m • \ 033 [0m "
echo  " "
echo -e " \ 033 [1; 31m \ 033 [1; 33m MAIN COMMAND: \ 033 [1; 32mmenu \ 033 [0m "
echo -e " \ 033 [1; 33m MAIS INFORMACOES \ 033 [1; 31m (\ 033 [1; 36mTELEGRAM \ 033 [1; 31m): \ 033 [1; 37m @ SSHPLUS \ 033 [0m "
rm $ HOME / Plus && cat / dev / null >  ~ /.bash_history &&  history -c
