#! / bin / bash
clear
echo -e " \ 033 [1; 32m DISSYSTALL OR SSHPLUS MANAGER \ 033 [1; 33m "
read -p " Do you want to Remove? [y / n] " resp
if [[ " $ resp "  = s ||  " $ resp "  = S]] ; then
    apt-get purge screen -y > / dev / null 2> & 1
    apt-get purge nmap -y > / dev / null 2> & 1
    apt-get purge figlet -y > / dev / null 2> & 1
    apt-get purge squid -y > / dev / null 2> & 1
    apt-get purge squid3 -y > / dev / null 2> & 1
    apt-get purge dropbear -y > / dev / null 2> & 1
    apt-get purge apache2 -y > / dev / null 2> & 1
    rm / bin / createuser / bin / expcleaner / bin / sshlimiter / bin / addhost / bin / list / bin / sshmonitor / bin / ajuda / bin / menu / bin / OpenVPN / bin / userbackup / bin / tcpspeed / bin / badvpn / bin / optimize / bin / speedtest / bin / trafego / bin / banner / bin / limit / bin / limit / bin / senharoot / bin / restart services / bin / restart system / bin / attscript / bin / criarteste / bin / socks / bin / DropBear / bin / alterlimit / bin / alterarsenha / bin / remove / bin / details / bin / mudardata / bin / botssh / bin / infousers / bin / droplimiter / bin / Conexao / bin / versao > / dev / null 2> & 1
    rm -rf / etc / SSHPlus > / dev / null 2> & 1
    clear
    echo -e " \ 033 [1; 36m Brigado to use or SSHPLUS MANAGER \ 033 [1; 33m "
    sleep 2
    cat / dev / null >  ~ /.bash_history &&  history -c &&  exit 0
else
    echo -e " \ 033 [1; 32mOk returning to menu \ 033 [1; 33m "
    sleep 3
    menu
fi
