#! / bin / bash

echo -e " \ 033 [1; 31mATENCAO !! \ 033 [0m "
echo  "  "
echo -e " \ 033 [1; 33mEssa senha will be used to enter not on your server
\ 033 [0m "
echo -e " \ 033 [1; 32mDIGITE TO NOVA SENHA \ 033 [1; 32m
to continue ... \ 033 [1; 31m \ 033 [0m "
read   -p : pass
(echo $ pass ;  echo  $ pass ) | passwd 2> / dev / null
sleep 1s
echo -e " \ 033 [1; 31mSENHA ALTERED COM SUCESSO! \ 033 [0m "
sleep 5s
CD
clear
